name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER_ID: ${{ secrets.SONATYPE_USERNAME }}
      USER_PWD: ${{ secrets.SONATYPE_PWD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: |
          wget https://raw.githubusercontent.com/eFaps/Utils/master/settings/settings.xml -O mySettings.xml
          mvn install -s mySettings.xml -DskipTests=true -B -U
      - name: Run Tests
        run: mvn test -s mySettings.xml -B
      - name: Deploy
        run: mvn deploy -DskipTests -s mySettings.xml


  trigger-dependend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: eFaps/eFaps-Core
          event-type: dependency-event



